### ISSUE TITLE
URGENT!!

### ISSUE THREAD

**Issue by ph4t0o0o0om** [bibhuticoder/realtimeBoard#2]
Hello Good day. I check the demo and it's good. BUT . when i try to run this on my computer the output is very different on demo and the whiteboard is not collaborative i have 2 browser open localhost:3000 and i try to draw on 1st browser but it not syncing on user2. Can you please fix this? Thank you!!!!

**Comment by bibhuticoder** [comment]
It would be easier if you provide the error log.

**Comment by ph4t0o0o0om** [comment]
Hi Good day. Actually no error. I follow the instructions but the output is far different from the DEMO APP you provide. Please help me pls
