### ISSUE TITLE
URGENT PART 2!!!!!

### ISSUE THREAD

**Issue by ph4t0o0o0om** [bibhuticoder/realtimeBoard#3]
Check the pictures. The 3rd picture is the project i import to my computer my own server. And the 1st and 2nd picture is your DEMO APP!! I thought your demo app and the source you provided is the same but it looks like far different. Is there any problem on my import? Or you just not give the right soure? Hope you help me thank you!!
![asdd1](https://user-images.githubusercontent.com/41504668/43814976-f3aadb56-9aff-11e8-821a-e19b85e28add.PNG)
![asdd2](https://user-images.githubusercontent.com/41504668/43814980-fa20f29a-9aff-11e8-9c98-a0cd313c3734.PNG)

![asdd](https://user-images.githubusercontent.com/41504668/43814964-e2dcf3fe-9aff-11e8-84b8-2269cd30a8be.PNG)

**Comment by bibhuticoder** [comment]
The demo is the latest one. It mostly includes UI chnages, the core features are same.
